### PR TITLE
[feature] Add a Top-Level Makefile

### PR DESCRIPTION
**Pull request by mark-burnett**
This adds a simple build process for building and pushing containers to quay.io that doesn't rely on their webhook mechanism and associated limits.

This should also allow developers to simply run `make build` in this repo to populate these images in their development environment.

---
This change is [Reviewable](https://reviewable.io/reviews/att-comdev/dockerfiles/95)

### CODE REVIEW

**Comment by mark-burnett** [comment]
Please review @intlabs and @v1k0d3n 

I didn't attempt to modify the `maas` images, because I thought it would be a distraction from this feature and seemed like more detailed context would be useful for that.

**Comment by intlabs** [comment]
Though I can't comment on any potential impact to quay.io builds, this LGTM :) nice one dude

**Comment by mark-burnett** [comment]
@v1k0d3n can you take a look this week?  I already pushed the RMQ image to quay.io using this branch.

**Review by v1k0d3n — APPROVED** [review]
LGTM. Thanks @mark-burnett. I can work on cleaning up the automated builds on quay.

**Pull request merged**
