### PR TITLE
Add container for RabbitMQ 3.7.0 pre-release (Milestone 14)

### PR DESCRIPTION
**Pull request by mark-burnett**
This image pulls a deb from the [RabbitMQ github](https://github.com/rabbitmq/rabbitmq-server/releases/tag/rabbitmq_v3_7_0_milestone14) and builds an image based on the existing [official 3.6 Dockerfile](
https://github.com/docker-library/rabbitmq).

### CODE REVIEW

**Comment by gardlt** [comment]
This Image is good can @intlabs @alanmeadows @v1k0d3n please review

**Comment by v1k0d3n** [comment]
@mark-burnett this looks really good. 

to this point we've been using automatic builds on quay (good eye btw), but this will actually only last for so long. quay limits the amount of webhook automatic builds to 20 per single repo, and we're going to hit that eventually. your makefile would be better served at the root of the `dockerfiles` repo, serving as a push mechanism for _all_ for our dockerfiles. then we could remove the automatic build triggers (which are currently limited to Quay), and properly CI the repo using Travis or something else. this reduces the debt of setting up webhooks and makes it easier to maintain pushes to both Quay and Docker Hub during each run. 

would you mine doing this? if you're cool with it, then just remove the makefile from this rabbitmq folder, recommit, and then i'll merge this in. then submit another PR for the makefile at the root of the repo. i'll reach out to Stacy tomorrow, tell her what our plans are for the past/future regarding CI, and then get her more up to speed. if you're busy or working on other things, i can find someone else who can continue with your idea.

thanks for the PR...again this is really good, and really happy to have you on the team!

**Review by v1k0d3n — COMMENTED** [review]
LGTM. waiting on @mark-burnett comments on my suggestions.

**Comment by mark-burnett** [comment]
@v1k0d3n Thanks for the review.

I definitely don't mind pulling out the Makefile and setting one up at the top level.

**Comment by mark-burnett** [comment]
@v1k0d3n I've removed the Makefile.  I'll start working on a top-level one next.

**Comment by intlabs** [comment]
LGTM :)

**Pull request merged**
