### PR TITLE
Create Kubeadm-AIO container

### PR DESCRIPTION
**Pull request by intlabs**
Adds a new container that deploys a Kubeadm based AIO Kubernetes environment.

---
This change is [Reviewable](https://reviewable.io/reviews/att-comdev/dockerfiles/82)

### CODE REVIEW

**Comment by intlabs** [comment]
This is required to support: https://github.com/att-comdev/openstack-helm/pull/304

@v1k0d3n: should I just update the image name to: `quay.io/attcomdev/kubeadm-aio` or would you prefer another tag?

**Comment by v1k0d3n** [comment]
@intlabs i think that works. i can find out if we've reached our webhook limit after this is merged in. Quay allows 20 webhooks per repo (used to be 25), which can make auto-building challenging for repos that have several containers. there are a couple of ways to address this though. if we reach the limit, we can explore them but I'm hoping/thinking we'll be fine.

**Review by v1k0d3n — APPROVED** [review]
LGTM @intlabs thanks for submitting this PR! :)

**Comment by v1k0d3n** [comment]
update: `quay.io/attcomdev/kubeadm-aio:v1.0.0` is now active and ready for use.

**Pull request merged**
